version: 2

models:
  - name: int_impute_bedrooms_wc
    columns:
      - name: Number_Of_Bedrooms_Imputed
        description: "Imputed number of bedrooms using business logic"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10
      - name: Number_Of_WC_Imputed
        description: "Imputed number of WC using business logic"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10

      - name: property_surrogate_key
        description: 'SK created with 6 columns'
        tests:
          - unique