version: 2

models:
  - name: int_impute_bedrooms_wc
    columns:
      - name: Bedrooms_Imputed
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
      - name: WC_Imputed
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 5