version: 2

models:
  - name: stg_raw_property_listings
    description: "Cleaned and filtered raw property listings"
    columns:
      # ========================================
      # 1. LIVING AREA: must be ≥ 30 (if not NULL)
      # ========================================
      - name: Living_Area
        description: "Living area in m²"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 30
              row_condition: "Living_Area IS NOT NULL"

      # ========================================
      # 2. LOT SIZE: must be ≥ 30 (if not NULL)
      # ========================================
      - name: Lot_Size
        description: "Lot size in m²"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 30
              row_condition: "Lot_Size IS NOT NULL"

      # ========================================
      # 3. PRICE: > 15,000
      # ========================================
      - name: Price
        description: "Property price in EUR"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_greater_than:
              value: 15000

      # ========================================
      # 4. CATEGORY: only valid types
      # ========================================
      - name: Category
        description: "Property type"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Apartment', 'House', 'Land']

      # ========================================
      # 5. CITY & TOWN: not null
      # ========================================
      - name: City
        tests:
          - not_null
      - name: Town
        tests:
          - not_null

      # ========================================
      # 6. IMPUTED COLUMNS (intermediate model)
      # ========================================
      - name: Bedrooms_Imputed
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: NUMBER
      - name: WC_Imputed
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: NUMBER