version: 2

models:
  - name: stg_raw_property_listings
    description: "Cleaned and filtered raw property listings"
    columns:
      # ========================================
      # 1. LIVING AREA: must be ≥ 30 (if not NULL)
      # ========================================
      - name: Living_Area
        description: "Living area in m²"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 30
                row_condition: "Living_Area IS NOT NULL"
      - name: Lot_Size
        description: "Lot size in m²"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 30
                row_condition: "Lot_Size IS NOT NULL"
      - name: Price
        description: "Property price in EUR"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 15000
                row_condition: "Price IS NOT NULL"
      - name: Category
        description: "Property type"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['Apartment', 'House', 'Land']

      # ========================================
      # 5. CITY & TOWN: not null
      # ========================================
      - name: City
        tests:
          - not_null
      - name: Town
        tests:
          - not_null