# models/staging/schema.yml
version: 2

models:
  - name: stg_raw_property_listings
    description: |
      **Staging model** -- first cleaning layer.
      
      * Safely casts numbers/dates
      * Standardizes text (Title Case + TRIM)
      * Filters to Apartment/House/Land
      * No deduplication yet

    columns:
      - name: City
        description: "City name (Title Case, trimmed). E.g., LISBOA"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "LENGTH(city) >= 3"

      - name: Town
        description: "Town/municipality (Title Case, trimmed)"
        tests:
          - not_null

      - name: District
        description: "District (Title Case, trimmed)"
        tests:
          - not_null

      - name: Category
        description: "Filtered to Apartment, House, Land"
        tests:
          - not_null
          - accepted_values:
              values: ['Apartment', 'House', 'Land']

      - name: Price
        description: "Price in EUR (decimal). NULL = failed parse"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "Price BETWEEN 10000 AND 50000000"

      - name: Construction Year
        description: "Year of construction. NULL = failed parse"
        tests:
          - dbt_utils.expression_is_true:
              expression: >
                Construction Year IS NULL OR 
                (Construction Year BETWEEN 1800 AND EXTRACT(YEAR FROM CURRENT_DATE) + 5)

      - name: Loaded_At
        description: "Timestamp when row was loaded into RAW"
        tests:
          - not_null