version: 2

models:
  - name: stg_raw_property_listings
    description: "Cleaned and filtered raw property listings"
    columns:
      - name: Price
        description: "Property price in EUR"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "Price > 15000"

      - name: Category
        description: "Property type: Apartment, House, Land"
        tests:
          - not_null
          - accepted_values:
              values: ['Apartment', 'House', 'Land']

      - name: City
        tests:
          - not_null

      - name: Town
        tests:
          - not_null

      - name: Living_Area
        description: "Living area in m²"
        tests:
          - dbt_utils.expression_is_true:
              expression: "Living_Area > 29 OR Living_Area IS NULL"

      - name: Lot_Size
        tests:
          - dbt_utils.expression_is_true:
              expression: "Lot_Size > 29 OR Lot_Size IS NULL"