version: 2

models:
  - name: overview  # This creates the homepage
    description: |
      # Portugal Real Estate Analytics

      **Project goal**: Transform raw property listings into trusted, dashboard-ready datasets.

      **Source**: `RAW.PROPERTY_LISTINGS_RAW` (135k+ listings)  
      **Updated**: Daily at 02:00 AM  
      **Owner**: Cristian Valenzuela  
      **Slack**: #portugal-real-estate

      ## Layers
      - **staging**: clean raw data
      - **intermediate**: price imputation + outlier removal
      - **marts**: final tables for Power BI / Tableau / Looker.

# Your existing model descriptions here...